# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screenAdmin_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Database import UnixSystem as db
from screenAdmin import Ui_AdminBooksWindow
import os, json

class Ui_AdminStudentsWindow(object):
    def openFiles(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AdminBooksWindow()
        self.ui.setupUi(self.window)
        self.window.hide()
        self.MainWindow.show()
    
    def clickAdmReturn(self):
        print("clicked :: button: push file")
        self.txtStuOut.setText("")
        ufileNo = self.edtfileNoReturn.text()
        uID = self.edtStuID.text()
        db.returnLoan(uID, ufileNo)
        self.txtStuOut.setText("file pushed successfully!")

    def clickAdmnLoan(self):
        print("clicked :: button: file retrieve")
        self.txtStuOut.setText("")
        ufileNo = self.edtfileNoReturn.text()
        uID = self.edtStuID.text()
        db.loanout(uID, ufileNo)
        self.txtStuOut.setText("file returned successfully!")

    def clickAdmnDel(self):
        print("clicked :: button: Delete user")
        uID = self.edtStuID.text()
        self.txtStuOut.setText("")
        db.deleteStudent(uID)
        self.txtStuOut.setText("User deleted!")
        self.textEdit.setText("")
        self.textEdit.setText(db.displaystudents(db.viewStudents()))

    def clickStuLoans(self):
        uID = self.edtStuID.text()
        self.textEdit_2.setText("")
        self.textEdit_2.setText(db.mybooks(uID))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 758)
        MainWindow.setMinimumSize(QtCore.QSize(961, 758))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameMenu = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMenu.sizePolicy().hasHeightForWidth())
        self.frameMenu.setSizePolicy(sizePolicy)
        self.frameMenu.setMinimumSize(QtCore.QSize(150, 550))
        self.frameMenu.setStyleSheet("background-color: rgb(150,81,12)")
        self.frameMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMenu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMenu.setLineWidth(0)
        self.frameMenu.setObjectName("frameMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameMenu)
        self.verticalLayout.setContentsMargins(15, 15, 15, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.line_3 = QtWidgets.QFrame(self.frameMenu)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pbtnBooks = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnBooks.sizePolicy().hasHeightForWidth())
        self.pbtnBooks.setSizePolicy(sizePolicy)
        self.pbtnBooks.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnBooks.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pbtnBooks.setFont(font)
        self.pbtnBooks.setMouseTracking(True)
        self.pbtnBooks.setAutoFillBackground(False)
        self.pbtnBooks.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: white;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/essential-icons/svg/book-433812.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnBooks.setIcon(icon)
        self.pbtnBooks.setIconSize(QtCore.QSize(25, 25))
        self.pbtnBooks.setCheckable(False)
        self.pbtnBooks.setAutoDefault(False)
        self.pbtnBooks.setDefault(False)
        self.pbtnBooks.setFlat(True)
        self.pbtnBooks.setObjectName("pbtnBooks")
        self.verticalLayout.addWidget(self.pbtnBooks)
        self.pbtnProfile = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnProfile.sizePolicy().hasHeightForWidth())
        self.pbtnProfile.setSizePolicy(sizePolicy)
        self.pbtnProfile.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnProfile.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnProfile.setFont(font)
        self.pbtnProfile.setMouseTracking(True)
        self.pbtnProfile.setAutoFillBackground(False)
        self.pbtnProfile.setStyleSheet("QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"background-color: rgb(228,182,136); \n"
"border: 1px solid rgb(228,182,136);\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/essential-icons/svg/user-433878.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnProfile.setIcon(icon1)
        self.pbtnProfile.setIconSize(QtCore.QSize(25, 25))
        self.pbtnProfile.setCheckable(False)
        self.pbtnProfile.setChecked(False)
        self.pbtnProfile.setAutoDefault(False)
        self.pbtnProfile.setDefault(False)
        self.pbtnProfile.setFlat(True)
        self.pbtnProfile.setObjectName("pbtnProfile")
        self.verticalLayout.addWidget(self.pbtnProfile)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"text-align: left;\n"
"color: white;\n"
"padding: 10px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  color: red;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/essential-icons/svg/cancel-433817.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout.addWidget(self.frameMenu)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(593, 548))
        self.frame.setStyleSheet("background-color: rgb(82,44,6)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hHeader = QtWidgets.QHBoxLayout()
        self.hHeader.setSpacing(0)
        self.hHeader.setObjectName("hHeader")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(228,182,136);")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.hHeader.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hHeader.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.hHeader)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.vSearch = QtWidgets.QVBoxLayout()
        self.vSearch.setContentsMargins(0, 0, 0, 0)
        self.vSearch.setObjectName("vSearch")
        self.edtStuID = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtStuID.sizePolicy().hasHeightForWidth())
        self.edtStuID.setSizePolicy(sizePolicy)
        self.edtStuID.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.edtStuID.setFont(font)
        self.edtStuID.setAutoFillBackground(False)
        self.edtStuID.setStyleSheet("\n"
"color: white;")
        self.edtStuID.setText("")
        self.edtStuID.setMaxLength(13)
        self.edtStuID.setFrame(False)
        self.edtStuID.setClearButtonEnabled(True)
        self.edtStuID.setObjectName("edtStuID")
        self.vSearch.addWidget(self.edtStuID)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(175, 140))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 175))
        self.tabWidget.setStyleSheet("QTabBar{\n"
"    color: black; \n"
"    background-color: rgb(82,44,6);\n"
"    width: 20px\n"
"}\n"
"\n"
"QTabBar::tab:selected \n"
"{ \n"
"    background-color: rgb(228,182,136);\n"
"    border-radius:7px;\n"
"    padding: 5px;\n"
"    color: black;\n"
"}\n"
"")
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 461, 141))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(75, 0))
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.edtfileNoReturn = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.edtfileNoReturn.setMinimumSize(QtCore.QSize(250, 0))
        self.edtfileNoReturn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtfileNoReturn.setAutoFillBackground(False)
        self.edtfileNoReturn.setStyleSheet("color: white;")
        self.edtfileNoReturn.setMaxLength(13)
        self.edtfileNoReturn.setFrame(False)
        self.edtfileNoReturn.setClearButtonEnabled(True)
        self.edtfileNoReturn.setObjectName("edtfileNoReturn")
        self.horizontalLayout_6.addWidget(self.edtfileNoReturn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.pbtnReturnStu = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnReturnStu.sizePolicy().hasHeightForWidth())
        self.pbtnReturnStu.setSizePolicy(sizePolicy)
        self.pbtnReturnStu.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnReturnStu.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnReturnStu.setFont(font)
        self.pbtnReturnStu.setMouseTracking(True)
        self.pbtnReturnStu.setAutoFillBackground(False)
        self.pbtnReturnStu.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/navigation-14/svg/check-1518584.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnReturnStu.setIcon(icon3)
        self.pbtnReturnStu.setIconSize(QtCore.QSize(25, 25))
        self.pbtnReturnStu.setCheckable(False)
        self.pbtnReturnStu.setChecked(False)
        self.pbtnReturnStu.setAutoDefault(False)
        self.pbtnReturnStu.setDefault(False)
        self.pbtnReturnStu.setFlat(True)
        self.pbtnReturnStu.setObjectName("pbtnReturnStu")
        self.verticalLayout_9.addWidget(self.pbtnReturnStu)
        self.tabWidget.addTab(self.tab, "")
        self.tabLoan = QtWidgets.QWidget()
        self.tabLoan.setObjectName("tabLoan")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabLoan)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(75, 0))
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.edtfileNoLoan = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edtfileNoLoan.setMinimumSize(QtCore.QSize(250, 0))
        self.edtfileNoLoan.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtfileNoLoan.setAutoFillBackground(False)
        self.edtfileNoLoan.setStyleSheet("color: white;")
        self.edtfileNoLoan.setMaxLength(13)
        self.edtfileNoLoan.setFrame(False)
        self.edtfileNoLoan.setClearButtonEnabled(True)
        self.edtfileNoLoan.setObjectName("edtfileNoLoan")
        self.horizontalLayout_3.addWidget(self.edtfileNoLoan)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.pbtnLoanStu = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnLoanStu.sizePolicy().hasHeightForWidth())
        self.pbtnLoanStu.setSizePolicy(sizePolicy)
        self.pbtnLoanStu.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnLoanStu.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnLoanStu.setFont(font)
        self.pbtnLoanStu.setMouseTracking(True)
        self.pbtnLoanStu.setAutoFillBackground(False)
        self.pbtnLoanStu.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        self.pbtnLoanStu.setIcon(icon3)
        self.pbtnLoanStu.setIconSize(QtCore.QSize(25, 25))
        self.pbtnLoanStu.setCheckable(False)
        self.pbtnLoanStu.setChecked(False)
        self.pbtnLoanStu.setAutoDefault(False)
        self.pbtnLoanStu.setDefault(False)
        self.pbtnLoanStu.setFlat(True)
        self.pbtnLoanStu.setObjectName("pbtnLoanStu")
        self.verticalLayout_5.addWidget(self.pbtnLoanStu)
        self.tabWidget.addTab(self.tabLoan, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 371, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.pbtnDelStu = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnDelStu.sizePolicy().hasHeightForWidth())
        self.pbtnDelStu.setSizePolicy(sizePolicy)
        self.pbtnDelStu.setMinimumSize(QtCore.QSize(91, 30))
        self.pbtnDelStu.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnDelStu.setFont(font)
        self.pbtnDelStu.setMouseTracking(True)
        self.pbtnDelStu.setAutoFillBackground(False)
        self.pbtnDelStu.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        self.pbtnDelStu.setIcon(icon3)
        self.pbtnDelStu.setIconSize(QtCore.QSize(25, 25))
        self.pbtnDelStu.setCheckable(False)
        self.pbtnDelStu.setChecked(False)
        self.pbtnDelStu.setAutoDefault(False)
        self.pbtnDelStu.setDefault(False)
        self.pbtnDelStu.setFlat(True)
        self.pbtnDelStu.setObjectName("pbtnDelStu")
        self.verticalLayout_7.addWidget(self.pbtnDelStu)
        self.tabWidget.addTab(self.widget, "")
        self.vSearch.addWidget(self.tabWidget)
        self.txtStuOut = QtWidgets.QTextEdit(self.frame)
        self.txtStuOut.setMaximumSize(QtCore.QSize(500, 50))
        self.txtStuOut.setStyleSheet("text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; ")
        self.txtStuOut.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txtStuOut.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txtStuOut.setDocumentTitle("")
        self.txtStuOut.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txtStuOut.setObjectName("txtStuOut")
        self.vSearch.addWidget(self.txtStuOut)
        self.verticalLayout_2.addLayout(self.vSearch)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabBooks = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabBooks.sizePolicy().hasHeightForWidth())
        self.tabBooks.setSizePolicy(sizePolicy)
        self.tabBooks.setMaximumSize(QtCore.QSize(800, 250))
        self.tabBooks.setStyleSheet("QTabBar{\n"
"    color: black; background-color: rgb(82,44,6);\n"
"}\n"
"\n"
"QTabBar::tab:selected \n"
"{ \n"
"    background-color: rgb(228,182,136);\n"
"    border-radius:7px;\n"
"    padding: 5px;\n"
"    color: black;\n"
"}\n"
"")
        self.tabBooks.setElideMode(QtCore.Qt.ElideRight)
        self.tabBooks.setUsesScrollButtons(False)
        self.tabBooks.setTabBarAutoHide(True)
        self.tabBooks.setObjectName("tabBooks")
        self.tabBooksList = QtWidgets.QWidget()
        self.tabBooksList.setObjectName("tabBooksList")
        self.textEdit = QtWidgets.QTextEdit(self.tabBooksList)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 791, 211))
        self.textEdit.setStyleSheet("color: white;")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setText(db.displaystudents(db.viewStudents()))
        self.tabBooks.addTab(self.tabBooksList, "")
        self.tabLoanList = QtWidgets.QWidget()
        self.tabLoanList.setObjectName("tabLoanList")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabLoanList)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 791, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(15, 15, -1, 15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbtnStuLoans = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnStuLoans.sizePolicy().hasHeightForWidth())
        self.pbtnStuLoans.setSizePolicy(sizePolicy)
        self.pbtnStuLoans.setMinimumSize(QtCore.QSize(91, 30))
        self.pbtnStuLoans.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnStuLoans.setFont(font)
        self.pbtnStuLoans.setMouseTracking(True)
        self.pbtnStuLoans.setAutoFillBackground(False)
        self.pbtnStuLoans.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/navigation-14/svg/refresh-1518571.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnStuLoans.setIcon(icon4)
        self.pbtnStuLoans.setIconSize(QtCore.QSize(25, 25))
        self.pbtnStuLoans.setCheckable(False)
        self.pbtnStuLoans.setChecked(False)
        self.pbtnStuLoans.setAutoDefault(False)
        self.pbtnStuLoans.setDefault(False)
        self.pbtnStuLoans.setFlat(True)
        self.pbtnStuLoans.setObjectName("pbtnStuLoans")
        self.horizontalLayout_4.addWidget(self.pbtnStuLoans)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.textEdit_2.setStyleSheet("color: white;")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_2.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_3.addWidget(self.textEdit_2)
        self.tabBooks.addTab(self.tabLoanList, "")
        self.verticalLayout_2.addWidget(self.tabBooks)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # ===========================================================================================
        # buttons clicked
        self.pbtnReturnStu.clicked.connect(self.clickAdmReturn)
        self.pbtnLoanStu.clicked.connect(self.clickAdmnLoan)
        self.pbtnDelStu.clicked.connect(self.clickAdmnDel)
        self.pbtnStuLoans.clicked.connect(self.clickStuLoans)
        self.pbtnBooks.clicked.connect(self.openFiles)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabBooks.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbtnBooks.setText(_translate("MainWindow", "files"))
        self.pbtnProfile.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnProfile.setText(_translate("MainWindow", "Users"))
        self.pushButton_3.setText(_translate("MainWindow", "Sign out"))
        self.label.setText(_translate("MainWindow", "Unix System | Admin"))
        self.edtStuID.setPlaceholderText(_translate("MainWindow", "Enter user ID here"))
        self.label_6.setText(_translate("MainWindow", "file no:"))
        self.edtfileNoReturn.setPlaceholderText(_translate("MainWindow", "Enter file no here"))
        self.pbtnReturnStu.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnReturnStu.setText(_translate("MainWindow", "Confirm "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Return"))
        self.label_2.setText(_translate("MainWindow", "file no:"))
        self.edtfileNoLoan.setPlaceholderText(_translate("MainWindow", "Enter file no here"))
        self.pbtnLoanStu.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnLoanStu.setText(_translate("MainWindow", "Confirm "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLoan), _translate("MainWindow", "Retrieve file"))
        self.pbtnDelStu.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnDelStu.setText(_translate("MainWindow", "Confirm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Delete User"))
        self.label_4.setText(_translate("MainWindow", "Lists"))
        self.tabBooks.setTabText(self.tabBooks.indexOf(self.tabBooksList), _translate("MainWindow", "Users List"))
        self.pbtnStuLoans.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnStuLoans.setText(_translate("MainWindow", " Report"))
        self.tabBooks.setTabText(self.tabBooks.indexOf(self.tabLoanList), _translate("MainWindow", "files available to users"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adminStudentsWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminStudentsWindow()
    ui.setupUi(adminStudentsWindow)
    adminStudentsWindow.show()
    sys.exit(app.exec_())
