# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screenAdmn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Database import UnixSystem as db
import os, json
from screenAdmin_2 import Ui_AdminStudentsWindow

class Ui_AdminBooksWindow(object):
    def openStudents(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AdminStudentsWindow()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

    def clickLoan(self):
        self.txtOut.setText("")
        ufileNo = self.edtfileNo.text()
        uID = self.edtIDLoan.text()
        db.loanout(uID, ufileNo)
        self.txtOut.setText("Book loaned successfully!")
        self.edtIDLoan.setText("")

        a,b = db.viewloans()
        outPut = db.displayloans(a,b)
        self.textEdit_2.setText(outPut)

    def clickReturn(self):
        self.txtOut.setText("")
        ufileNo = self.edtfileNo.text()
        uID = self.edtIDReturn.text()
        db.returnLoan(uID, ufileNo)
        self.txtOut.setText("Book returned successfully!")
        self.edtIDLoan.setText("")

        a,b = db.viewloans()
        outPut = db.displayloans(a,b)
        self.textEdit_2.setText(outPut)

    def clickDel(self):
        self.txtOut.setText("")
        ufileNo = self.edtfileNo.text()
        db.deleteBook(ufileNo)
        self.txtOut.setText("Book deleted successfully!")
        self.edtIDLoan.setText("")

        self.textEdit.setText("")
        outPut = db.displaybooks(db.viewBooks())
        self.textEdit.setText(outPut)

    def clickAdd(self):
        self.txtOut.setText("")
        ufileNo = self.edtfileNo.text()
        uTitle = self.edtTitle.text()
        uAuthor = self.edtAuthor.text()
        uCategory = self.edtCategory.text()
        uYear = self.edtYear.text()
        db.AddBook(ufileNo,uTitle,uAuthor,uCategory,uYear)
        self.txtOut.setText("Book added successfully!")
        self.edtIDLoan.setText("")

        self.textEdit.setText("")
        outPut = db.displaybooks(db.viewBooks())
        self.textEdit.setText(outPut)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 758)
        MainWindow.setMinimumSize(QtCore.QSize(961, 758))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameMenu = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMenu.sizePolicy().hasHeightForWidth())
        self.frameMenu.setSizePolicy(sizePolicy)
        self.frameMenu.setMinimumSize(QtCore.QSize(150, 550))
        self.frameMenu.setStyleSheet("background-color: rgb(150,81,12)")
        self.frameMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMenu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMenu.setLineWidth(0)
        self.frameMenu.setObjectName("frameMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameMenu)
        self.verticalLayout.setContentsMargins(15, 15, 15, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.line_3 = QtWidgets.QFrame(self.frameMenu)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pbtnBooks = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnBooks.sizePolicy().hasHeightForWidth())
        self.pbtnBooks.setSizePolicy(sizePolicy)
        self.pbtnBooks.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnBooks.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pbtnBooks.setFont(font)
        self.pbtnBooks.setMouseTracking(True)
        self.pbtnBooks.setAutoFillBackground(False)
        self.pbtnBooks.setStyleSheet("QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"background-color: rgb(228,182,136); \n"
"border: 1px solid rgb(228,182,136);\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/essential-icons/svg/book-433812.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnBooks.setIcon(icon)
        self.pbtnBooks.setIconSize(QtCore.QSize(25, 25))
        self.pbtnBooks.setCheckable(False)
        self.pbtnBooks.setAutoDefault(False)
        self.pbtnBooks.setDefault(False)
        self.pbtnBooks.setFlat(True)
        self.pbtnBooks.setObjectName("pbtnBooks")
        self.verticalLayout.addWidget(self.pbtnBooks)
        self.pbtnStudents = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnStudents.sizePolicy().hasHeightForWidth())
        self.pbtnStudents.setSizePolicy(sizePolicy)
        self.pbtnStudents.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnStudents.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnStudents.setFont(font)
        self.pbtnStudents.setMouseTracking(True)
        self.pbtnStudents.setAutoFillBackground(False)
        self.pbtnStudents.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: white;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/essential-icons/svg/user-433878.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnStudents.setIcon(icon1)
        self.pbtnStudents.setIconSize(QtCore.QSize(25, 25))
        self.pbtnStudents.setCheckable(False)
        self.pbtnStudents.setChecked(False)
        self.pbtnStudents.setAutoDefault(False)
        self.pbtnStudents.setDefault(False)
        self.pbtnStudents.setFlat(True)
        self.pbtnStudents.setObjectName("pbtnStudents")
        self.verticalLayout.addWidget(self.pbtnStudents)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"text-align: left;\n"
"color: white;\n"
"padding: 10px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  color: red;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/essential-icons/svg/cancel-433817.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout.addWidget(self.frameMenu)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(593, 548))
        self.frame.setStyleSheet("background-color: rgb(82,44,6)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hHeader = QtWidgets.QHBoxLayout()
        self.hHeader.setSpacing(0)
        self.hHeader.setObjectName("hHeader")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(228,182,136);")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.hHeader.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hHeader.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.hHeader)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.vSearch = QtWidgets.QVBoxLayout()
        self.vSearch.setContentsMargins(0, 0, 0, 0)
        self.vSearch.setObjectName("vSearch")
        self.edtfileNo = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtfileNo.sizePolicy().hasHeightForWidth())
        self.edtfileNo.setSizePolicy(sizePolicy)
        self.edtfileNo.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.edtfileNo.setFont(font)
        self.edtfileNo.setAutoFillBackground(False)
        self.edtfileNo.setStyleSheet("\n"
"color: white;")
        self.edtfileNo.setText("")
        self.edtfileNo.setMaxLength(4)
        self.edtfileNo.setFrame(False)
        self.edtfileNo.setClearButtonEnabled(True)
        self.edtfileNo.setObjectName("edtfileNo")
        self.vSearch.addWidget(self.edtfileNo)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(175, 140))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 175))
        self.tabWidget.setStyleSheet("QTabBar{\n"
"    color: black; \n"
"    background-color: rgb(82,44,6);\n"
"    width: 20px\n"
"}\n"
"\n"
"QTabBar::tab:selected \n"
"{ \n"
"    background-color: rgb(228,182,136);\n"
"    border-radius:7px;\n"
"    padding: 5px;\n"
"    color: black;\n"
"}\n"
"")
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 461, 141))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(75, 0))
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.edtIDReturn = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.edtIDReturn.setMinimumSize(QtCore.QSize(250, 0))
        self.edtIDReturn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtIDReturn.setAutoFillBackground(False)
        self.edtIDReturn.setStyleSheet("color: white;")
        self.edtIDReturn.setMaxLength(13)
        self.edtIDReturn.setFrame(False)
        self.edtIDReturn.setClearButtonEnabled(True)
        self.edtIDReturn.setObjectName("edtIDReturn")
        self.horizontalLayout_6.addWidget(self.edtIDReturn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.pbtnReturn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnReturn.sizePolicy().hasHeightForWidth())
        self.pbtnReturn.setSizePolicy(sizePolicy)
        self.pbtnReturn.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnReturn.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnReturn.setFont(font)
        self.pbtnReturn.setMouseTracking(True)
        self.pbtnReturn.setAutoFillBackground(False)
        self.pbtnReturn.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/navigation-14/svg/check-1518584.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnReturn.setIcon(icon3)
        self.pbtnReturn.setIconSize(QtCore.QSize(25, 25))
        self.pbtnReturn.setCheckable(False)
        self.pbtnReturn.setChecked(False)
        self.pbtnReturn.setAutoDefault(False)
        self.pbtnReturn.setDefault(False)
        self.pbtnReturn.setFlat(True)
        self.pbtnReturn.setObjectName("pbtnReturn")
        self.verticalLayout_9.addWidget(self.pbtnReturn)
        self.tabWidget.addTab(self.tab, "")
        self.tabLoan = QtWidgets.QWidget()
        self.tabLoan.setObjectName("tabLoan")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabLoan)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(75, 0))
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.edtIDLoan = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edtIDLoan.setMinimumSize(QtCore.QSize(250, 0))
        self.edtIDLoan.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtIDLoan.setAutoFillBackground(False)
        self.edtIDLoan.setStyleSheet("color: white;")
        self.edtIDLoan.setMaxLength(13)
        self.edtIDLoan.setFrame(False)
        self.edtIDLoan.setClearButtonEnabled(True)
        self.edtIDLoan.setObjectName("edtIDLoan")
        self.horizontalLayout_3.addWidget(self.edtIDLoan)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.pbtnLoan = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnLoan.sizePolicy().hasHeightForWidth())
        self.pbtnLoan.setSizePolicy(sizePolicy)
        self.pbtnLoan.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnLoan.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnLoan.setFont(font)
        self.pbtnLoan.setMouseTracking(True)
        self.pbtnLoan.setAutoFillBackground(False)
        self.pbtnLoan.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        self.pbtnLoan.setIcon(icon3)
        self.pbtnLoan.setIconSize(QtCore.QSize(25, 25))
        self.pbtnLoan.setCheckable(False)
        self.pbtnLoan.setChecked(False)
        self.pbtnLoan.setAutoDefault(False)
        self.pbtnLoan.setDefault(False)
        self.pbtnLoan.setFlat(True)
        self.pbtnLoan.setObjectName("pbtnLoan")
        self.verticalLayout_5.addWidget(self.pbtnLoan)
        self.tabWidget.addTab(self.tabLoan, "")
        self.tabReturn = QtWidgets.QWidget()
        self.tabReturn.setObjectName("tabReturn")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabReturn)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 791, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.edtTitle = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.edtTitle.setMinimumSize(QtCore.QSize(275, 0))
        self.edtTitle.setMaximumSize(QtCore.QSize(275, 16777215))
        self.edtTitle.setAutoFillBackground(False)
        self.edtTitle.setStyleSheet("color: white;")
        self.edtTitle.setText("")
        self.edtTitle.setFrame(False)
        self.edtTitle.setClearButtonEnabled(True)
        self.edtTitle.setObjectName("edtTitle")
        self.horizontalLayout_4.addWidget(self.edtTitle)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(75, 0))
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.edtAuthor = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.edtAuthor.setMinimumSize(QtCore.QSize(250, 0))
        self.edtAuthor.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtAuthor.setAutoFillBackground(False)
        self.edtAuthor.setStyleSheet("color: white;")
        self.edtAuthor.setFrame(False)
        self.edtAuthor.setClearButtonEnabled(True)
        self.edtAuthor.setObjectName("edtAuthor")
        self.horizontalLayout_4.addWidget(self.edtAuthor)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(75, 0))
        self.label_8.setStyleSheet("color: white;")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.edtCategory = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.edtCategory.setMinimumSize(QtCore.QSize(275, 0))
        self.edtCategory.setMaximumSize(QtCore.QSize(275, 16777215))
        self.edtCategory.setAutoFillBackground(False)
        self.edtCategory.setStyleSheet("color: white;")
        self.edtCategory.setText("")
        self.edtCategory.setFrame(False)
        self.edtCategory.setClearButtonEnabled(True)
        self.edtCategory.setObjectName("edtCategory")
        self.horizontalLayout_7.addWidget(self.edtCategory)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(75, 0))
        self.label_9.setStyleSheet("color: white;")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.edtYear = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.edtYear.setMinimumSize(QtCore.QSize(250, 0))
        self.edtYear.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtYear.setAutoFillBackground(False)
        self.edtYear.setStyleSheet("color: white;")
        self.edtYear.setFrame(False)
        self.edtYear.setClearButtonEnabled(True)
        self.edtYear.setObjectName("edtYear")
        self.horizontalLayout_7.addWidget(self.edtYear)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.pbtnAdd = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnAdd.sizePolicy().hasHeightForWidth())
        self.pbtnAdd.setSizePolicy(sizePolicy)
        self.pbtnAdd.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnAdd.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnAdd.setFont(font)
        self.pbtnAdd.setMouseTracking(True)
        self.pbtnAdd.setAutoFillBackground(False)
        self.pbtnAdd.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        self.pbtnAdd.setIcon(icon3)
        self.pbtnAdd.setIconSize(QtCore.QSize(25, 25))
        self.pbtnAdd.setCheckable(False)
        self.pbtnAdd.setChecked(False)
        self.pbtnAdd.setAutoDefault(False)
        self.pbtnAdd.setDefault(False)
        self.pbtnAdd.setFlat(True)
        self.pbtnAdd.setObjectName("pbtnAdd")
        self.verticalLayout_6.addWidget(self.pbtnAdd)
        self.tabWidget.addTab(self.tabReturn, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 371, 141))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.pbtnDel = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnDel.sizePolicy().hasHeightForWidth())
        self.pbtnDel.setSizePolicy(sizePolicy)
        self.pbtnDel.setMinimumSize(QtCore.QSize(91, 30))
        self.pbtnDel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnDel.setFont(font)
        self.pbtnDel.setMouseTracking(True)
        self.pbtnDel.setAutoFillBackground(False)
        self.pbtnDel.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        self.pbtnDel.setIcon(icon3)
        self.pbtnDel.setIconSize(QtCore.QSize(25, 25))
        self.pbtnDel.setCheckable(False)
        self.pbtnDel.setChecked(False)
        self.pbtnDel.setAutoDefault(False)
        self.pbtnDel.setDefault(False)
        self.pbtnDel.setFlat(True)
        self.pbtnDel.setObjectName("pbtnDel")
        self.verticalLayout_7.addWidget(self.pbtnDel)
        self.tabWidget.addTab(self.widget, "")
        self.vSearch.addWidget(self.tabWidget)
        self.txtOut = QtWidgets.QTextEdit(self.frame)
        self.txtOut.setMaximumSize(QtCore.QSize(500, 50))
        self.txtOut.setStyleSheet("text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; ")
        self.txtOut.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txtOut.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txtOut.setDocumentTitle("")
        self.txtOut.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txtOut.setObjectName("txtOut")
        self.vSearch.addWidget(self.txtOut)
        self.verticalLayout_2.addLayout(self.vSearch)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabBooks = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabBooks.sizePolicy().hasHeightForWidth())
        self.tabBooks.setSizePolicy(sizePolicy)
        self.tabBooks.setMaximumSize(QtCore.QSize(800, 250))
        self.tabBooks.setStyleSheet("QTabBar{\n"
"    color: black; background-color: rgb(82,44,6);\n"
"}\n"
"\n"
"QTabBar::tab:selected \n"
"{ \n"
"    background-color: rgb(228,182,136);\n"
"    border-radius:7px;\n"
"    padding: 5px;\n"
"    color: black;\n"
"}\n"
"")
        self.tabBooks.setElideMode(QtCore.Qt.ElideRight)
        self.tabBooks.setUsesScrollButtons(False)
        self.tabBooks.setTabBarAutoHide(True)
        self.tabBooks.setObjectName("tabBooks")
        self.tabBooksList = QtWidgets.QWidget()
        self.tabBooksList.setObjectName("tabBooksList")
        self.textEdit = QtWidgets.QTextEdit(self.tabBooksList)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 791, 211))
        self.textEdit.setStyleSheet("color: white;")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.tabBooks.addTab(self.tabBooksList, "")
        self.tabLoanList = QtWidgets.QWidget()
        self.tabLoanList.setObjectName("tabLoanList")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tabLoanList)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 791, 211))
        self.textEdit_2.setStyleSheet("color: white;")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_2.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabBooks.addTab(self.tabLoanList, "")
        self.verticalLayout_2.addWidget(self.tabBooks)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # ===========================================================================================
        # Display Books table

        self.textEdit.setText("")
        outPut = db.displaybooks(db.viewBooks())
        self.textEdit.setText(outPut)

        # ===========================================================================================
        # Display Loans table

        self.textEdit_2.setText("")
        a,b = db.viewloans()
        print("a-b ",a)
        outPut = db.displayloans(a,b)
        self.textEdit_2.setText(outPut)

        # ===========================================================================================
        # buttons clicked
        self.pbtnLoan.clicked.connect(self.clickLoan)
        self.pbtnReturn.clicked.connect(self.clickReturn)
        self.pbtnDel.clicked.connect(self.clickDel)
        self.pbtnAdd.clicked.connect(self.clickAdd)
        self.pbtnStudents.clicked.connect(self.openStudents)


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabBooks.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbtnBooks.setText(_translate("MainWindow", "files"))
        self.pbtnStudents.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnStudents.setText(_translate("MainWindow", "Users"))
        self.pushButton_3.setText(_translate("MainWindow", "Sign out"))
        self.label.setText(_translate("MainWindow", "Unix System | Admin"))
        self.edtfileNo.setPlaceholderText(_translate("MainWindow", "Enter file no here"))
        self.label_6.setText(_translate("MainWindow", "Student ID:"))
        self.edtIDReturn.setPlaceholderText(_translate("MainWindow", "Enter user ID here"))
        self.pbtnReturn.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnReturn.setText(_translate("MainWindow", "Confirm "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Return"))
        self.label_2.setText(_translate("MainWindow", "user ID:"))
        self.edtIDLoan.setPlaceholderText(_translate("MainWindow", "Enter user ID here"))
        self.pbtnLoan.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnLoan.setText(_translate("MainWindow", "Confirm "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLoan), _translate("MainWindow", "push file"))
        self.label_3.setText(_translate("MainWindow", "Title:"))
        self.edtTitle.setPlaceholderText(_translate("MainWindow", "Enter title here"))
        self.label_7.setText(_translate("MainWindow", "Author:"))
        self.edtAuthor.setPlaceholderText(_translate("MainWindow", "Enter author here"))
        self.label_8.setText(_translate("MainWindow", "Category:"))
        self.edtCategory.setPlaceholderText(_translate("MainWindow", "Enter category here"))
        self.label_9.setText(_translate("MainWindow", "Year:"))
        self.edtYear.setPlaceholderText(_translate("MainWindow", "Enter year here"))
        self.pbtnAdd.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnAdd.setText(_translate("MainWindow", "Confirm "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReturn), _translate("MainWindow", "Add file"))
        self.pbtnDel.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnDel.setText(_translate("MainWindow", "Confirm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Delete file"))
        self.label_4.setText(_translate("MainWindow", "Lists"))
        self.tabBooks.setTabText(self.tabBooks.indexOf(self.tabBooksList), _translate("MainWindow", "files list"))
        self.tabBooks.setTabText(self.tabBooks.indexOf(self.tabLoanList), _translate("MainWindow", "files available to users"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminBooksWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
