# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screenSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Database import UnixSystem as db
import os, json
from screenAdmin import Ui_AdminBooksWindow

class Ui_StudentSearchWindow(object):
    def clickSLoan(self):
        self.txt_SOut.setText("")
        ufileNo = self.edtfileNo_SLoan.text()
        uID = self.edtID_SLoan.text()
        db.loanout(uID, ufileNo)
        print("file retrieved")
        self.txt_SOut.setText("file retrived successfully!")

    def clickSReturn(self):
        self.txt_SOut.setText("")
        ufileNo = self.edtfileNo_SLoan.text()
        uID = self.edtID_SLoan.text()
        db.returnLoan(uID, ufileNo)
        print("file returned")
        self.txt_SOut.setText("file returned successfully!")

    def clickSearch(self):
        self.txtEdit_Search.setText("")
        searchtext = self.edtSearch.text()
        if (self.rbtnTitle.isChecked() == True):
            self.txtEdit_Search.setText(db.displaybooks(db.SearchTitle(searchtext)))
        elif (self.rbtnCategory.isChecked() == True):
            self.txtEdit_Search.setText(db.displaybooks(db.SearchCat(searchtext)))
        elif (self.rbtnYear.isChecked() == True):
            self.txtEdit_Search.setText(db.displaybooks(db.SearchYear(searchtext)))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 789)
        MainWindow.setMinimumSize(QtCore.QSize(961, 789))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameMenu = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameMenu.sizePolicy().hasHeightForWidth())
        self.frameMenu.setSizePolicy(sizePolicy)
        self.frameMenu.setMinimumSize(QtCore.QSize(150, 550))
        self.frameMenu.setStyleSheet("background-color: rgb(150,81,12)")
        self.frameMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMenu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMenu.setLineWidth(0)
        self.frameMenu.setObjectName("frameMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameMenu)
        self.verticalLayout.setContentsMargins(15, 15, 15, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.line_3 = QtWidgets.QFrame(self.frameMenu)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pbtnProfile = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnProfile.sizePolicy().hasHeightForWidth())
        self.pbtnProfile.setSizePolicy(sizePolicy)
        self.pbtnProfile.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnProfile.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnProfile.setFont(font)
        self.pbtnProfile.setMouseTracking(True)
        self.pbtnProfile.setAutoFillBackground(False)
        self.pbtnProfile.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: white;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/essential-icons/svg/user-433878.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnProfile.setIcon(icon)
        self.pbtnProfile.setIconSize(QtCore.QSize(25, 25))
        self.pbtnProfile.setCheckable(False)
        self.pbtnProfile.setChecked(False)
        self.pbtnProfile.setAutoDefault(False)
        self.pbtnProfile.setDefault(False)
        self.pbtnProfile.setFlat(True)
        self.pbtnProfile.setObjectName("pbtnProfile")
        self.verticalLayout.addWidget(self.pbtnProfile)
        self.pbtnBooks = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnBooks.sizePolicy().hasHeightForWidth())
        self.pbtnBooks.setSizePolicy(sizePolicy)
        self.pbtnBooks.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnBooks.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pbtnBooks.setFont(font)
        self.pbtnBooks.setMouseTracking(True)
        self.pbtnBooks.setAutoFillBackground(False)
        self.pbtnBooks.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"background-color: rgb(228,182,136); \n"
"border: 1px solid rgb(228,182,136);\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/essential-icons/svg/book-433812.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnBooks.setIcon(icon1)
        self.pbtnBooks.setIconSize(QtCore.QSize(25, 25))
        self.pbtnBooks.setCheckable(False)
        self.pbtnBooks.setAutoDefault(False)
        self.pbtnBooks.setDefault(False)
        self.pbtnBooks.setFlat(True)
        self.pbtnBooks.setObjectName("pbtnBooks")
        self.verticalLayout.addWidget(self.pbtnBooks)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frameMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"text-align: left;\n"
"color: white;\n"
"padding: 10px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  color: red;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/essential-icons/svg/cancel-433817.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout.addWidget(self.frameMenu)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(593, 548))
        self.frame.setStyleSheet("background-color: rgb(82,44,6)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hHeader = QtWidgets.QHBoxLayout()
        self.hHeader.setSpacing(0)
        self.hHeader.setObjectName("hHeader")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(228,182,136);")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.hHeader.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hHeader.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.hHeader)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.vSearch = QtWidgets.QVBoxLayout()
        self.vSearch.setContentsMargins(0, 0, 0, 0)
        self.vSearch.setObjectName("vSearch")
        self.edtSearch = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSearch.sizePolicy().hasHeightForWidth())
        self.edtSearch.setSizePolicy(sizePolicy)
        self.edtSearch.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.edtSearch.setFont(font)
        self.edtSearch.setAutoFillBackground(False)
        self.edtSearch.setStyleSheet("\n"
"color: white;")
        self.edtSearch.setText("")
        self.edtSearch.setMaxLength(333333)
        self.edtSearch.setFrame(False)
        self.edtSearch.setClearButtonEnabled(True)
        self.edtSearch.setObjectName("edtSearch")
        self.vSearch.addWidget(self.edtSearch)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.rbtnTitle = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtnTitle.sizePolicy().hasHeightForWidth())
        self.rbtnTitle.setSizePolicy(sizePolicy)
        self.rbtnTitle.setAutoFillBackground(False)
        self.rbtnTitle.setStyleSheet("color: white;")
        self.rbtnTitle.setChecked(True)
        self.rbtnTitle.setObjectName("rbtnTitle")
        self.btngroupSearchby = QtWidgets.QButtonGroup(MainWindow)
        self.btngroupSearchby.setObjectName("btngroupSearchby")
        self.btngroupSearchby.addButton(self.rbtnTitle)
        self.horizontalLayout_5.addWidget(self.rbtnTitle)
        self.rbtnCategory = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtnCategory.sizePolicy().hasHeightForWidth())
        self.rbtnCategory.setSizePolicy(sizePolicy)
        self.rbtnCategory.setStyleSheet("color: white;")
        self.rbtnCategory.setObjectName("rbtnCategory")
        self.btngroupSearchby.addButton(self.rbtnCategory)
        self.horizontalLayout_5.addWidget(self.rbtnCategory)
        self.rbtnYear = QtWidgets.QRadioButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtnYear.sizePolicy().hasHeightForWidth())
        self.rbtnYear.setSizePolicy(sizePolicy)
        self.rbtnYear.setStyleSheet("color: white;")
        self.rbtnYear.setObjectName("rbtnYear")
        self.btngroupSearchby.addButton(self.rbtnYear)
        self.horizontalLayout_5.addWidget(self.rbtnYear)
        spacerItem3 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.vSearch.addLayout(self.horizontalLayout_5)
        self.pbtn_SSearch = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtn_SSearch.sizePolicy().hasHeightForWidth())
        self.pbtn_SSearch.setSizePolicy(sizePolicy)
        self.pbtn_SSearch.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtn_SSearch.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtn_SSearch.setFont(font)
        self.pbtn_SSearch.setMouseTracking(True)
        self.pbtn_SSearch.setAutoFillBackground(False)
        self.pbtn_SSearch.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/file-and-folder-14/svg/search-file-1214211.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtn_SSearch.setIcon(icon3)
        self.pbtn_SSearch.setIconSize(QtCore.QSize(25, 25))
        self.pbtn_SSearch.setCheckable(False)
        self.pbtn_SSearch.setChecked(False)
        self.pbtn_SSearch.setAutoDefault(False)
        self.pbtn_SSearch.setDefault(False)
        self.pbtn_SSearch.setFlat(True)
        self.pbtn_SSearch.setObjectName("pbtn_SSearch")
        self.vSearch.addWidget(self.pbtn_SSearch)
        self.txtEdit_Search = QtWidgets.QTextEdit(self.frame)
        self.txtEdit_Search.setMaximumSize(QtCore.QSize(800, 50))
        self.txtEdit_Search.setStyleSheet("color: white;")
        self.txtEdit_Search.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txtEdit_Search.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txtEdit_Search.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txtEdit_Search.setObjectName("txtEdit_Search")
        self.vSearch.addWidget(self.txtEdit_Search)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.vSearch.addWidget(self.label_2)
        self.txtEdit_Books = QtWidgets.QTextEdit(self.frame)
        self.txtEdit_Books.setMinimumSize(QtCore.QSize(0, 200))
        self.txtEdit_Books.setMaximumSize(QtCore.QSize(800, 250))
        self.txtEdit_Books.setStyleSheet("color: white;")
        self.txtEdit_Books.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txtEdit_Books.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txtEdit_Books.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txtEdit_Books.setObjectName("txtEdit_Books")
        self.vSearch.addWidget(self.txtEdit_Books)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(175, 150))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 200))
        self.tabWidget.setStyleSheet("QTabBar{\n"
"    color: black; \n"
"    background-color: rgb(82,44,6);\n"
"    width: 20px\n"
"}\n"
"\n"
"QTabBar::tab:selected \n"
"{ \n"
"    background-color: rgb(228,182,136);\n"
"    border-radius:7px;\n"
"    padding: 5px;\n"
"    color: black;\n"
"}\n"
"")
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 461, 111))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(75, 0))
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.edtID_SReturn = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.edtID_SReturn.setMinimumSize(QtCore.QSize(250, 0))
        self.edtID_SReturn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtID_SReturn.setAutoFillBackground(False)
        self.edtID_SReturn.setStyleSheet("color: white;")
        self.edtID_SReturn.setMaxLength(13)
        self.edtID_SReturn.setFrame(False)
        self.edtID_SReturn.setClearButtonEnabled(True)
        self.edtID_SReturn.setObjectName("edtID_SReturn")
        self.horizontalLayout_7.addWidget(self.edtID_SReturn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(75, 0))
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.edtfileNo_SReturn = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.edtfileNo_SReturn.setMinimumSize(QtCore.QSize(250, 0))
        self.edtfileNo_SReturn.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtfileNo_SReturn.setAutoFillBackground(False)
        self.edtfileNo_SReturn.setStyleSheet("color: white;")
        self.edtfileNo_SReturn.setMaxLength(13)
        self.edtfileNo_SReturn.setFrame(False)
        self.edtfileNo_SReturn.setClearButtonEnabled(True)
        self.edtfileNo_SReturn.setObjectName("edtfileNo_SReturn")
        self.horizontalLayout_6.addWidget(self.edtfileNo_SReturn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.pbtnSReturn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnSReturn.sizePolicy().hasHeightForWidth())
        self.pbtnSReturn.setSizePolicy(sizePolicy)
        self.pbtnSReturn.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnSReturn.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnSReturn.setFont(font)
        self.pbtnSReturn.setMouseTracking(True)
        self.pbtnSReturn.setAutoFillBackground(False)
        self.pbtnSReturn.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/navigation-14/svg/check-1518584.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbtnSReturn.setIcon(icon4)
        self.pbtnSReturn.setIconSize(QtCore.QSize(25, 25))
        self.pbtnSReturn.setCheckable(False)
        self.pbtnSReturn.setChecked(False)
        self.pbtnSReturn.setAutoDefault(False)
        self.pbtnSReturn.setDefault(False)
        self.pbtnSReturn.setFlat(True)
        self.pbtnSReturn.setObjectName("pbtnSReturn")
        self.verticalLayout_9.addWidget(self.pbtnSReturn)
        self.tabWidget.addTab(self.tab, "")
        self.tabLoan = QtWidgets.QWidget()
        self.tabLoan.setObjectName("tabLoan")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabLoan)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 461, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(75, 0))
        self.label_8.setStyleSheet("color: white;")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.edtID_SLoan = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edtID_SLoan.setMinimumSize(QtCore.QSize(250, 0))
        self.edtID_SLoan.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtID_SLoan.setAutoFillBackground(False)
        self.edtID_SLoan.setStyleSheet("color: white;")
        self.edtID_SLoan.setMaxLength(13)
        self.edtID_SLoan.setFrame(False)
        self.edtID_SLoan.setClearButtonEnabled(True)
        self.edtID_SLoan.setObjectName("edtID_SLoan")
        self.horizontalLayout_8.addWidget(self.edtID_SLoan)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(75, 0))
        self.label_9.setStyleSheet("color: white;")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.edtfileNo_SLoan = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edtfileNo_SLoan.setMinimumSize(QtCore.QSize(250, 0))
        self.edtfileNo_SLoan.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edtfileNo_SLoan.setAutoFillBackground(False)
        self.edtfileNo_SLoan.setStyleSheet("color: white;")
        self.edtfileNo_SLoan.setMaxLength(13)
        self.edtfileNo_SLoan.setFrame(False)
        self.edtfileNo_SLoan.setClearButtonEnabled(True)
        self.edtfileNo_SLoan.setObjectName("edtfileNo_SLoan")
        self.horizontalLayout_9.addWidget(self.edtfileNo_SLoan)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.pbtnSLoan = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtnSLoan.sizePolicy().hasHeightForWidth())
        self.pbtnSLoan.setSizePolicy(sizePolicy)
        self.pbtnSLoan.setMinimumSize(QtCore.QSize(0, 30))
        self.pbtnSLoan.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(True)
        self.pbtnSLoan.setFont(font)
        self.pbtnSLoan.setMouseTracking(True)
        self.pbtnSLoan.setAutoFillBackground(False)
        self.pbtnSLoan.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; \n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  background-color: rgb(241,218,195);\n"
"  color: black;\n"
"}\n"
"QPushButton:checked\n"
"{\n"
"  background-color: rgb(133,179,225);\n"
"  color: black;\n"
"}")
        self.pbtnSLoan.setIcon(icon4)
        self.pbtnSLoan.setIconSize(QtCore.QSize(25, 25))
        self.pbtnSLoan.setCheckable(False)
        self.pbtnSLoan.setChecked(False)
        self.pbtnSLoan.setAutoDefault(False)
        self.pbtnSLoan.setDefault(False)
        self.pbtnSLoan.setFlat(True)
        self.pbtnSLoan.setObjectName("pbtnSLoan")
        self.verticalLayout_5.addWidget(self.pbtnSLoan)
        self.tabWidget.addTab(self.tabLoan, "")
        self.vSearch.addWidget(self.tabWidget)
        self.txt_SOut = QtWidgets.QTextEdit(self.frame)
        self.txt_SOut.setMaximumSize(QtCore.QSize(500, 35))
        self.txt_SOut.setStyleSheet("text-align: left;\n"
"color: black;\n"
"padding: 10px;\n"
"border-radius:7px;\n"
"padding: 5px;\n"
"background-color: white; ")
        self.txt_SOut.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_SOut.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_SOut.setDocumentTitle("")
        self.txt_SOut.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.txt_SOut.setObjectName("txt_SOut")
        self.vSearch.addWidget(self.txt_SOut)
        self.verticalLayout_2.addLayout(self.vSearch)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # ===========================================================================================
        # Display Books table

        self.txtEdit_Books.setText("")
        outPut = db.displaybooks(db.viewBooks())
        self.txtEdit_Books.setText(outPut)

        # ============================= Button Clicks ==========================================================
        self.pbtnSLoan.clicked.connect(self.clickSLoan)
        self.pbtnSReturn.clicked.connect(self.clickSReturn)
        self.pbtn_SSearch.clicked.connect(self.clickSearch)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbtnProfile.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnProfile.setText(_translate("MainWindow", "My Profile"))
        self.pbtnBooks.setText(_translate("MainWindow", "File Management"))
        self.pushButton_3.setText(_translate("MainWindow", "Sign out"))
        self.label.setText(_translate("MainWindow", "Unix System "))
        self.edtSearch.setPlaceholderText(_translate("MainWindow", "Files on server:"))
        self.label_5.setText(_translate("MainWindow", "Search by:"))
        self.rbtnTitle.setText(_translate("MainWindow", "Title"))
        self.rbtnCategory.setText(_translate("MainWindow", "Category"))
        self.rbtnYear.setText(_translate("MainWindow", "Year"))
        self.pbtn_SSearch.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtn_SSearch.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Available files"))
        self.label_7.setText(_translate("MainWindow", "Confirm ID:"))
        self.edtID_SReturn.setPlaceholderText(_translate("MainWindow", "Enter your ID here"))
        self.label_6.setText(_translate("MainWindow", "file no"))
        self.edtfileNo_SReturn.setPlaceholderText(_translate("MainWindow", "Enter file no here"))
        self.pbtnSReturn.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnSReturn.setText(_translate("MainWindow", "Confirm "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Return"))
        self.label_8.setText(_translate("MainWindow", "Confirm ID:"))
        self.edtID_SLoan.setPlaceholderText(_translate("MainWindow", "Enter your ID here"))
        self.label_9.setText(_translate("MainWindow", "file no"))
        self.edtfileNo_SLoan.setPlaceholderText(_translate("MainWindow", "Enter file no here"))
        self.pbtnSLoan.setWhatsThis(_translate("MainWindow", "\'My Profile\' button"))
        self.pbtnSLoan.setText(_translate("MainWindow", "Confirm "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLoan), _translate("MainWindow", "retrieve file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentBooksWindow = QtWidgets.QMainWindow()
    ui = Ui_StudentSearchWindow()
    ui.setupUi(studentBooksWindow)
    studentBooksWindow.show()
    sys.exit(app.exec_())
